In [1]:
import numpy as np

NUmpy의 많은 기능들(합계, 평균, 표준편차, ...)은 함수와 ndarray의 클래스의 메서드로 구현되어 있음

* np.function_name(arg, ...)
* ndarray.method_name(arg, ...)

In [2]:
# 함수 정의
def test_fn(arg):
    print(f'Hello, {arg}!')

# 함수 호출
test_fn('function')

Hello, function!


In [6]:
# 클래스 정의
class MyClass:
    # 메서드 정의
    def test_method(self, arg):
        print(f'Hello, {arg}!')

# MyClass 클래스의 인스턴스 생성
cls = MyClass()
# 인스턴스가 메서드를 호출 
cls.test_method('method')

Hello, method!


In [8]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
np.sum(arr)  # 함수 호출

55

In [12]:
arr.sum()  # ndarray 객체(인스턴스)의 메서드를 호춣

55

In [23]:
# numpy의 통계 관련 함수/메서드
print(arr)
print('합계:', np.sum(arr), arr.sum())
print('평균:', np.mean(arr), arr.mean())
print('분산:', np.var(arr), arr.var())
print('표준편차:', np.std(arr), arr.std())
print('최댓값:', np.max(arr), arr.max())
print('최솟값:', np.min(arr), arr.min())
print('중앙값:', np.median(arr))
#> numpy.media() 함수는 있지만, numpy.ndarray.median() 메서드는 없음!

[ 1  2  3  4  5  6  7  8  9 10]
합계: 55 55
평균: 5.5 5.5
분산: 8.25 8.25
표준편차: 2.8722813232690143 2.8722813232690143
최댓값: 10 10
최솟값: 1 1
중앙값: 5.5


In [28]:
# numpy.max(), numpy.min() 함수와 numpy.maximum(), numpy.minimum() 함수의 차이
# numpy.max(arra): array의 최댓값을 리턴
# numpy.maximum(a1, a2): 배열(과 비슷한 객체) a1, a2의 같은 인덱스에 있는 원소들 중에서 최댓값들로 이루어진 배열

np.random.seed(1)
a1 = np.random.randint(0, 20, size=10)
print(a1)
a2 = np.random.randint(0, 20, size=10)
print(a2)

print('a1 max:', np.max(a1))    # a1.max()
print('a2 max:', np.max(a2))    # a2.max()
print(np.maximum(a1, a2))

[ 5 11 12  8  9 11  5 15  0 16]
[ 1 12  7 13  6 18  5 18 11 10]
a1 max: 16
a2 max: 18
[ 5 12 12 13  9 18  5 18 11 16]


In [31]:
# np.argmax(array), ndarray.argmax(): 배열의 최댓값의 위치(인덱스)를 리턴
# np.argmin(array), ndarray.argmin(): 배열의 최솟값을 위치(인덱스)를 리턴
print(a2)
print('argmax:', np.argmax(a2), a2.argmax())
print('argmin:', np.argmin(a2), a2.argmin())

[ 1 12  7 13  6 18  5 18 11 10]
argmax: 5 5
argmin: 0 0


In [42]:
# 0 이상 100 미만의 정수 10개로 이루어진 1-d ndarray를 생성
np.random.seed(42)
array = np.random.randint(0, 100, size=10)
print(array)
print(array.mean())    # np.mean(array)

# array에서 원소들의 평균보다 큰 값으로 이루어진 1-d array를 찾음 
print(array[array > array.mean()])  # np.mean(array)


[51 92 14 71 60 20 82 86 74 74]
62.4
[92 71 82 86 74 74]


In [50]:
# 2-d ndarray의 통계 관련 함수/메서드
np.random.seed(1)
array = np.random.randint(0, 10, size=(4, 5))
print(array)

# sum
print(np.sum(array))  # 
print(np.sum(array, axis=0))  #> 원소가 5개인 1-d ndarray 
print(np.sum(array, axis=1))  #> 원소가 4개인 1-d ndarray 
print(np.sum(array, axis=0, keepdims=True))
print(np.sum(array, axis=1, keepdims=True))

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]
 [2 4 7 7 9]]
96
[ 9 17 28 20 22]
[27 23 17 29]
[[ 9 17 28 20 22]]
[[27]
 [23]
 [17]
 [29]]
